# Generated by Django 3.0.8 on 2020-07-23 16:30

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='joined_at',
        ),
        migrations.AddField(
            model_name='profile',
            name='facebook_profile',
            field=models.URLField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='instagram_profile',
            field=models.URLField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None),
        ),
        migrations.AddField(
            model_name='profile',
            name='twitter_profile',
            field=models.URLField(max_length=250, null=True),
        ),
    ]
