# Generated by Django 3.0.8 on 2020-07-23 16:35

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200723_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='facebook_profile',
            field=models.URLField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='instagram_profile',
            field=models.URLField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
        migrations.AlterField(
            model_name='profile',
            name='twitter_profile',
            field=models.URLField(blank=True, max_length=250, null=True),
        ),
    ]
