# Generated by Django 3.0.8 on 2020-08-03 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_about'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='facebook_profile',
            new_name='facebook_page',
        ),
        migrations.AlterField(
            model_name='profile',
            name='about',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
