# Generated by Django 3.0.8 on 2020-08-03 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200802_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='facebook_page',
            field=models.URLField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='instagram_profile',
            field=models.URLField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='twitter_profile',
            field=models.URLField(blank=True, max_length=150, null=True),
        ),
    ]
