# Generated by Django 3.0.8 on 2020-08-10 02:05

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200803_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='facebook_page',
            field=models.URLField(blank=True, max_length=150, null=True, validators=[accounts.validators.validate_facebook_url]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='instagram_profile',
            field=models.URLField(blank=True, max_length=150, null=True, validators=[accounts.validators.validate_instagram_url]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='twitter_profile',
            field=models.URLField(blank=True, max_length=150, null=True, validators=[accounts.validators.validate_twitter_url]),
        ),
    ]
