# Generated by Django 3.0.8 on 2020-07-24 23:52

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='thumbnail',
            field=models.ImageField(default='img/blog_thumbnails/default.jpg', upload_to=blog.models.upload_location),
        ),
    ]
