# Generated by Django 3.0.8 on 2020-07-25 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200724_2012'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogcomment',
            old_name='blog',
            new_name='article',
        ),
    ]
