# Generated by Django 3.0.8 on 2020-07-25 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200724_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcategory',
            name='tag_color',
            field=models.CharField(choices=[('ISL', 'is-light'), ('ISD', 'is-dark'), ('ISP', 'is-primary'), ('ISL', 'is-link'), ('ISI', 'is-info'), ('ISS', 'is-success'), ('ISW', 'is-warning'), ('ISD', 'is-danger')], default=('ISF', 'is-info'), max_length=10),
        ),
    ]
