# Generated by Django 3.0.8 on 2020-07-25 18:40

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200724_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcategory',
            name='tag_color',
            field=models.CharField(choices=[('ISL', 'is-light'), ('ISP', 'is-primary'), ('ISL', 'is-link'), ('ISI', 'is-info'), ('ISS', 'is-success'), ('ISW', 'is-warning'), ('ISD', 'is-danger')], default='is-light', max_length=10),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='thumbnail',
            field=models.ImageField(upload_to=blog.models.upload_location),
        ),
    ]
