# Generated by Django 3.0.8 on 2020-07-29 01:32

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200725_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='thumbnail',
            field=models.ImageField(default='img/blog_thumbnails/default.jpg', upload_to=blog.models.upload_location),
        ),
    ]
