# Generated by Django 3.0.8 on 2020-08-10 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20200729_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcomment',
            name='message',
            field=models.CharField(max_length=600),
        ),
    ]
