# Generated by Django 3.0.8 on 2020-08-11 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20200809_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='introduction',
            field=models.TextField(default='Lorem ipsum dolor sit amet, consectetur adipisicing elit. Est facilis ea, ducimus accusantium officiis soluta! Nam aperiam, assumenda repudiandae dolorem praesentium? ', max_length=400),
        ),
    ]
